### ISSUE TITLE
Cannot rebuild the lectures

### ISSUE THREAD

**Issue by mquinson** [alegrand/SMPE#2]
```
$ cd lectures
$ touch 1_reproducible_research.org
$ make
[lots of emacs' loading messages]
No language for src block: (unnamed)
Makefile:19: recipe for target '1_reproducible_research.tex' failed
make: *** [1_reproducible_research.tex] Error 255
```

That's not really reproducible, my friend ;)

**Comment by alegrand** [comment]
Actually, I just tried from a fresh git clone on my machine and it worked like a charm. I think the error message you get is due to the fact that your emacs may be trying to reexecute the blocks and some have no language associated (as they're just here to show simple code snippets). In my emacs configuration, I have:
  (setq org-export-babel-evaluate nil)
  (setq org-confirm-babel-evaluate nil)
I'll try to add it to the Makefile and close this issue. Do not hesitate to reopen it if it's ineffective...
